### ISSUE TITLE
[Events] Rename AddingEvent to ReferenceAddingEvent

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#16]
- **For**
    - This is not self-explanatory: `void handleAdding(@Observes AddingEvent event)`
    - This is: `void handleAdding(@Observes ReferenceAddingEvent event)`
    - Matches `ReferenceServiceObjects`   
- **Against**
    - The specification caters to users that have learned it
        - I.e. know what `AddingEvent` is.
- **Suggestion**
    - Rename it.

**Comment by rotty3000** [comment]
.. not bad... I kind of like it!

**Comment by pkriens** [comment]
OK with me. However, I think we have to have a rule. This works for a configuration and a service? I tend to use Reference for both and then ServiceReference and ConfigurationReference. However, the API is not structured like this?

**Comment by rotty3000** [comment]
Currently we haven't defined an event for configuration, but it would probably make sense to do so?

**Comment by pkriens** [comment]
Yes, I think we need to more seriously look at the symmetry between configuration and services. Except for cardinality they are identical in processing

**Comment by rotty3000** [comment]
`ReferenceAddingEvent<S>` doesn't give nice space for a future `ConfigurationEvent`, as @pkriens stated, there's not much symmetry

So what about good old `ServiceEvent<S>` which does good symmetry to future `ConfigurationEvent`.

It would be great to have a `ConfigurationEvent` to be honest... because how many times have I wished there was a `org.osgi.service.cm.ConfigurationTracker` which was very like `ServiceTracker`... but in the future.

**Comment by rotty3000** [comment]
so to clarify the suggestion is to go back to `ServiceEvent<S>` as the name of this event type.

**Comment by rinswind** [comment]
In the spec and API we consistently:
- Use "Reference" when referring to consuming services
- Use "Service" when referring to providing services

`ServiceEvent<T>` can cause confusion with `@Service` . `ReferenceEvent<T>` perhaps?
In the DTOs too I purposefully use `ReferenceDTO`, `ReferenceTemplateDTO` etc.

**Comment by rotty3000** [comment]
Ok, so then we are left with possibly these:

`ReferenceEvent<T>` and `ConfigurationEvent`

It doesn't not address @pkriens argument, but I'm ok with those choices at this time.

**Comment by rotty3000** [comment]
I think I will take a unilateral decision here and go with `ReferenceEvent<S>` because:

1. while it doesn't address @pkriens' concern about applicability of the term `reference` on both `service` dependencies and `configuration` dependencies, it does sync with the `@Reference` annotation which refers to the same concept of `service` dependency throughout the rest of our developer experience.
2. adding a `ConfigurationEvent` (potentially) at some point would sync with the `@Configuration` annotation in the same way.
3. I'm not sure anymore that a `ConfigurationEvent` will _ever_ make sense because configuration dependencies are never treated as a dynamic dependencies. Thus the components involved are always recycled. Events on the other hand are meant for the dynamic use case, so I'm not sure there's ever a feasible scenario for _dynamic configuration_.

With all that in mind, I'm going to proceed this way.

**Comment by rotty3000** [comment]
changed the API
