### ISSUE TITLE
[References] How to set the reference required scope?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#2]
- **Current**
    - unrestricted: add nothing
    - singleton: n/a
    - bundle: `@Bundle @Reference`
        - Is it `(|(service.scope=bundle)(service.scope=singleton))`?
        - Or `(service.scope=bundle)`
    - prototype: `@Prototype @Reference`
        - `(service.scope=prototype)`
- **Suggestion**
    - Only allow `@Prototype @Reference`
    - For everything else consume one object regardless of the scope.
    - If the user wants to force bundle or singleton they can use the target filter

**Comment by rotty3000** [comment]
One never specifies @Bundle on @Reference. There's no reason on the client side of a service request to asks for a distinction between singleton & bundle. The only sensible thing to ask for is prototype because it makes specific sense to require this at times. DS is exactly like this. It doesn't give you a facility to ask distinctly for singleton or bundle... Just prototype.

**Comment by rinswind** [comment]
The `@Bundle` javadoc says:
```
 * When used with
 * {@link Reference @Reference} or {@link AddingEvent AddingEvent} indicates
 * that the service must be {@code service.scope=bundle}.
```
I removed it and am closing the issue.

**Comment by rotty3000** [comment]
:+1:
