### ISSUE TITLE
[Configuration] How does Component.NAME work?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#27]
- **Suggestion**
    - Only one `@PID` or `@FactoryPID` on an `@Component` can have it.

**Comment by pkriens** [comment]
If not explicitly set, is the component name the lifecycle PID? For factories the instance pid and for non-factories the PID?

**Comment by rinswind** [comment]
@pkriens If I understand you correctly - yes.
@rotty3000 I know of the renaming, but had to retain the issue name the same as in the original file.

**Comment by rotty3000** [comment]
@pkriens this is what I expect:

* results in a definition error because the SAME pid was used for both singleton and factory pids (this is something we need to check for in general):
```
@Component
@PID // defaults to CDI_COMPONENT_NAME
@FactoryPID // defaults to CDI_COMPONENT_NAME
class Foo {}
```

* this is OK, the `CDI_COMPONENT_NAME` is the factory pid:
```
@Component
@PID("foo")
@FactoryPID // defaults to CDI_COMPONENT_NAME
class Foo {}
````

* this is OK, the CDI_COMPONENT_NAME is just a singleton PID:
```
@Component
@PID // defaults to CDI_COMPONENT_NAME
@FactoryPID("foo")
class Foo {}
````

**Comment by rotty3000** [comment]
Does this make sense to everyone?

**Comment by pkriens** [comment]
I am not sure I see the difference between first and second? 
I think that when there is a @FactoryPID it always wins? Only when there is no FactoryPID, the first PID wins.

**Comment by rinswind** [comment]
@rotty3000:  This makes sense.

@pkriens @rotty3000 Does Config Admin permit a singleton configuration and a factory configuration to have the same PID? I.e. does it keep the PID namespaces separate?

@rotty3000 @pkriens I propose we enforce that no two PIDs can be equal. I.e. gather all `@PID` and the the `@FactoryPID` and verify there are no duplicates in the list. This will automatically pick up the case where either of these defaults to the component name.

**Comment by pkriens** [comment]
The relation between a singleton + factory pid is a bit weird and this is sometimes visible in Webconsole.
Since you register both the MS and the MSF with "service.pid" it implies they share the same namespace. A primary idea of the PID is that it is a persistent identity, it is illogical when two services with the same PID do not represent the same thing. 

However, in config admin these namespaces are 100% separated. In CA the singleton PID is used as primary key. The factory is used for grouping, instances of a factory have a calculated singleton pid that is the primary key.

I.e. when you go from an MS to an MSF you lose the original configuration and it is not in the way. 

Should have been better designed although the whole model is quite powerful. Or maybe it should have been formally specified :-)

**Comment by rinswind** [comment]
I think we should enforce one PID namespace even if config admin doesn't.

**Comment by rotty3000** [comment]
If what I understand is that, even though CA allows the same PID to be both singleton and factory, our list of `@PID`s + `@FactoryPID` should maintain uniqueness, then I agree, so that developer doesn't get confused.

**Comment by rotty3000** [comment]
I think I understand what @pkriens was saying so let me clarify:

1. when no `@PID`/`@FactoryPID`, the lifecycle PID is the component name.
2. when @FactoryPID, this is the lifecycle PID
3. otherwise use the first @PID as the lifecycle pid
4. any duplication of values in any of @PIDs + @FactoryPID results in definition error

**Comment by rinswind** [comment]
Point (4.) completes this issue.
The rest are a separate issue: #38

**Comment by rotty3000** [comment]
closing as added to the spec draft.

we can debate further on bugzilla
