### ISSUE TITLE
[dto][runtime] Clarify how users must get the runtime DTOs (by Bundle only?)

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#41]
The DS `ServiceComponentRuntime` has the pattern:
- From a `Bundle` get a `ComponentDescriptionDTO`
- From a `ComponentDescriptionDTO` get a `ComponentConfigurationDTO`

Where
- `ComponentDescriptionDTO` is our `ContainerTemplateDTO`
- `ComponentConfiguratinDTO` is our `ContainerDTO`

At present we only have getters that take a `Bundle`.
- `CdiRuntime.getContainerTemplateDTO(Bundle)`
- `CdiRuntime.getContainerDTO(Bundle)`

Should we conform to the DS way?

Also we have the `ContainerTemplateDTO#id` so we can use that:
`CdiRuntime.getContainerDTO(String id)` 
rather than
`CdiRuntime.getContainerDTO(ContainerTemplateDTO)`

DS can't do that because they have many components per bundle so no simple key.

**Comment by rotty3000** [comment]
1. __Regarding id__: during the EEG we discussed using the plain BSN as the container id, which means it MAY be possible for more than one bundle to have the same id (e.g. multiple versions of the same bundle) and therefore we should not use the id as unique key.

2. __Regarding using the `ContainerTemplateDTO` as argument to get `ContainerDTO`__: In DS using the `ComponentDescriptionDTO` as argument to lookup `ComponentConfigurationDTO` is reasonable because `CDescriptionDTO` is already very light (it is not deeply nested). On the other hand, in CDI the `ContainerTemplateDTO` is relatively deeply nested and may have reasonably high cost to build. For this reason I believe our current design of using the `Bundle` is the best for both cases, uniqueness, and cost of construction.

**Comment by rinswind** [comment]
This settles the question for me.
We need an action to update the javadocs

**Comment by rotty3000** [comment]
updated the javadoc
