### ISSUE TITLE
[References] Remove @Filter

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#5]
- **Suggestion**
    - Use a component property `<reference name>.target` like with the `<reference name>.cardinality`
    - The main way to specify a filter are property annotations
        - E.g. `@Inject @OrgExampleProperty("some value") @Reference Hello hello;`

**Comment by rotty3000** [comment]
I'd rather not do this. It's really ugly and verbose for most developers to have to do this.

**Comment by rinswind** [comment]
After we removed `@Property`  we force developers to do this for component properties.  I think component properties are more common then the target filter. If we are doing it for component properties there should be no issue to do it for target filters?

**Comment by rotty3000** [comment]
I disagree! First of all, @Target is for use on @Reference. When do you ever see properties on @Reference? I think it will be rare for someone to actually use component property types on @Reference. Furthermore, we also need @Target for `ReferenceAddingEvent` for which we are making @Reference not required.

Furthermore, you would be forcing each and every @Reference to create a custom annotation in order to match the reference name because the reference name is unique per reference. I don't think this a viable solution.

@Filter is a convenience for developers.

**Comment by rotty3000** [comment]
As agreed at the EEG meetings in San Jose, I'm moving @Filter back to `@Reference(target = ...)`
